### ISSUE TITLE
Crypto domain in the address bar instead of IPFS hash

### ISSUE THREAD

**Issue by rluks** [unstoppabledomains/resolution-browser-extension#20]
I was wondering, would it be possible to keep the crypto domain in the browser address bar after redirecting to IPFS hash? I feel like it would improve user experience. When browsing the crypto domain they would still see it in the address bar. Thoughts?

**Comment by JohnnyJumper** [comment]
Hi @rluks, this is one of our future updates. At the moment we can't change the address URL after redirecting due to security issues, but we are looking into doh settings in modern browsers. They do allow us just resolve .crypto domains from blockchain via HTTPS instead of traditional DNS and the URL stays the same. You can experiment with these settings using this guide:
https://www.howtogeek.com/660088/how-to-enable-dns-over-https-in-google-chrome/

For resolving .crypto websites you can try https://eth.resolver.cloudflare-eth.com/dns-query this service. We probably create a different service that will resolve not only .crypto but .zil as well and update the extension to give users an option to enable it.

**Comment by JohnnyJumper** [comment]
Unfortunately, browsers are not allowing extensions to switch the URL of the page without being redirected. This is a security issue that makes it hard for others to do a fishing attack. We won't proceed with doing it until there is a solution that suits both browsers and extension users. 

I will close this issue for now. Feel free to open a new one if there is an update.
