### ISSUE TITLE
Automatically allow access on the following sites

### ISSUE THREAD

**Issue by aquiladev** [unstoppabledomains/resolution-browser-extension#21]
I see that the extension ask user for access to big list of sites. Why does it need the access?

<img width="732" alt="Screenshot 2021-05-11 at 12 49 34" src="https://user-images.githubusercontent.com/1164492/117796660-f78c5480-b257-11eb-8fde-dd6c62ee35e4.png">

**Comment by JohnnyJumper** [comment]
Those are the search engines added to the extension. We need those permission to be able to catch the default search requests and redirect users to an ipfs website instead of the search page. This is ultimately what allows our users to write brad.crypto and click enter without worrying about anything. Without them, the extension won't be able to catch the URL and users will end up on their default search engine page.
